require("bpisano.packer")

-- Core
require("bpisano.core.options")
require("bpisano.core.keymaps")
require("bpisano.core.keymaps-plugin")
require("bpisano.core.colorscheme")

-- Plugins
require("bpisano.plugins.nvim-comment")
require("bpisano.plugins.nvim-tree")
require("bpisano.plugins.lualine")
require("bpisano.plugins.barbecue")
require("bpisano.plugins.telescope")
require("bpisano.plugins.nvim-cmp")
require("bpisano.plugins.lsp")
require("bpisano.plugins.autopairs")
require("bpisano.plugins.indent-blank-line")
require("bpisano.plugins.better-comments")
require("bpisano.plugins.treesitter")
require("bpisano.plugins.trouble")
require("bpisano.plugins.illuminate")
require("bpisano.plugins.gitsigns")
require("bpisano.plugins.toggleterm")
require("bpisano.plugins.harpoon")
require("bpisano.plugins.chatgpt")
require("bpisano.plugins.hop")
require("bpisano.plugins.rainbow-delimiters")
require("bpisano.plugins.copilot")
require("bpisano.plugins.vim-godot")
